version: '3'

services:

  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - island

networks:
  island:

volumes:
  pg-data:
